### ISSUE TITLE
Vala support broke the panel

### ISSUE THREAD

**Issue by philipzae** [schuellerf/xfce-test#19]
When refreshing to today's latest build, the top and bottom panels were missing and the size of the container is 1GB smaller than the one from 6 weeks ago.

![image](https://user-images.githubusercontent.com/4412114/82565835-206d9280-9b8c-11ea-99fb-8ee3fce1f50f.png)

**Comment by schuellerf** [comment]
The first is a problem I'm working on. It's related to my try to activate the existing vala support which seemed to break the Panel
The 1GB size reduction is just a result of my optimizations of the docker build. Nothing was removed (rather some more things added)

**Comment by schuellerf** [comment]
...btw I've no experience with vala and its problems with symbol resolution during the build and runtime but I'll try to fix it somehow

**Comment by philipzae** [comment]
i've mentioned it in the xfce irc channel, so hopefully someone will come and assist.

Is there a means for me to run a previous latest build, possibly the one you built on May 1st.

**Comment by schuellerf** [comment]
It should be working now - please test again

**Comment by philipzae** [comment]
Unfortunately still broken as panels don't appear.

![image](https://user-images.githubusercontent.com/4412114/82742544-b235f500-9d70-11ea-82cd-400341045ecf.png)

![image](https://user-images.githubusercontent.com/4412114/82742506-3f2c7e80-9d70-11ea-92c1-6a5c6e30b183.png)

**Comment by philipzae** [comment]
Pulled today and it seems to be working (panels are appearing), though maybe some additional tweaks are needed as i tried to run the about app from the menu and it wouldnt open, so ran it from the terminal and then it opened.

**Comment by schuellerf** [comment]
I think those are not related to vala and I'll be working on those things anyway
